# Generated by Django 4.2.3 on 2024-06-30 10:56

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours_start', models.CharField(max_length=10, verbose_name='ish boshlanish vaqti')),
                ('working_hours_end', models.CharField(max_length=10, verbose_name='ish tugash vaqti')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('price', models.BigIntegerField(verbose_name='narxi')),
                ('order', models.IntegerField(verbose_name='buyurtma')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='activligi')),
            ],
            options={
                'verbose_name': 'mahsulot',
                'verbose_name_plural': 'mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='FreeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours_start', models.CharField(max_length=10, verbose_name='ish boshlanish vaqti')),
                ('working_hours_end', models.CharField(max_length=10, verbose_name='ish tugash vaqti')),
                ('product', models.BigIntegerField(verbose_name='product')),
                ('count', models.BigIntegerField(verbose_name='count')),
                ('free_count', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
