# Generated by Django 5.0.6 on 2024-06-27 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('content', models.TextField(verbose_name='content')),
                ('price', models.BigIntegerField(verbose_name='narxi')),
                ('order', models.IntegerField(verbose_name='buyurtma')),
            ],
        ),
        migrations.CreateModel(
            name='FreeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.BigIntegerField(verbose_name='product')),
                ('count', models.BigIntegerField(verbose_name='count')),
                ('free_count', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
