# Generated by Django 4.2.3 on 2024-07-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_freeproduct_working_hours_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freeproduct',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='freeproduct',
            old_name='updated_add',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_add',
            new_name='updated_at',
        ),
    ]
