# Generated by Django 5.0.6 on 2024-06-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_content_ru_product_content_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'mahsulot', 'verbose_name_plural': 'mahsulotlar'},
        ),
    ]
