# Generated by Django 4.2.3 on 2024-07-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_created_add_freeproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeproduct',
            name='created_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freeproduct',
            name='updated_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
