# Generated by Django 5.0.6 on 2024-06-27 12:21

import ckeditor_uploader.fields
import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=common.models.upload_to, verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'Galery/',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', verbose_name='slug')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name_plural': 'Posts/',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours_start', models.CharField(max_length=10, verbose_name='ish boshlanish vaqti')),
                ('working_hours_end', models.CharField(max_length=10, verbose_name='ish tugash vaqti')),
                ('contact_telegram', models.CharField(default=0, max_length=100, verbose_name='contact telegram')),
                ('contact_phone', models.CharField(max_length=15, verbose_name='contact phone')),
                ('longitude', models.FloatField(verbose_name='uzunlik')),
                ('latitute', models.FloatField(verbose_name='kenglik')),
                ('location_text', models.TextField(verbose_name='location text')),
                ('telegram_bot', models.CharField(max_length=100, verbose_name='telegram bot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
