# Generated by Django 4.2.3 on 2024-07-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_created_add_galleryphoto_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='created_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='updated_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='created_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='updated_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
