# Generated by Django 5.0.6 on 2024-06-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='soni')),
                ('free_count', models.BigIntegerField(default=0, verbose_name='tekinlari soni')),
                ('longitude', models.FloatField(verbose_name='uzunlik')),
                ('latetude', models.FloatField(verbose_name='kenglik')),
                ('status', models.CharField(choices=[('created', 'created'), ('in progress', 'in progress'), ('on the way', 'on the way'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], max_length=250, verbose_name='status')),
                ('product_price', models.BigIntegerField(verbose_name='product price')),
                ('total_price', models.BigIntegerField(verbose_name='total price')),
                ('status_changed_ad', models.BigIntegerField(verbose_name='statusga ozgarish qoshish')),
            ],
        ),
    ]
