# Generated by Django 4.2.3 on 2024-06-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours_start', models.CharField(max_length=10, verbose_name='ish boshlanish vaqti')),
                ('working_hours_end', models.CharField(max_length=10, verbose_name='ish tugash vaqti')),
                ('count', models.IntegerField(verbose_name='soni')),
                ('free_count', models.BigIntegerField(default=0, verbose_name='tekinlari soni')),
                ('longitude', models.FloatField(verbose_name='uzunlik')),
                ('latetude', models.FloatField(verbose_name='kenglik')),
                ('status', models.CharField(choices=[('tayyorlanmoqda', 'tayyorlanmoqda'), ("yo'lda", "yo'lda"), ('yetib keldi', 'yetib keldi'), ('yetkaziy yakunlandi', 'yatkazish yakunlandi')], max_length=250, verbose_name='status')),
                ('product_price', models.BigIntegerField(verbose_name='product price')),
                ('total_price', models.BigIntegerField(verbose_name='total price')),
                ('status_changed_ad', models.BigIntegerField(verbose_name='statusga ozgarish qoshish')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
